# Generated by Django 3.0.8 on 2020-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('risk', models.SmallIntegerField(verbose_name='风险偏好')),
                ('health', models.SmallIntegerField(verbose_name='健康度')),
                ('energy', models.SmallIntegerField(verbose_name='精力值')),
                ('happiness', models.SmallIntegerField(verbose_name='快乐度')),
                ('wisdom', models.SmallIntegerField(verbose_name='智力')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField()),
                ('good_name', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态 0-市场 ')),
                ('type', models.SmallIntegerField(verbose_name='类型 0-实物 1-股票 2-虚拟物品')),
                ('stock', models.IntegerField(verbose_name='库存量')),
                ('owner_id', models.IntegerField(verbose_name='拥有者 0-匿名市场货物  ')),
                ('isOnsale', models.SmallIntegerField(default=0, verbose_name='是否在售')),
                ('producer', models.IntegerField(default=0, verbose_name='生产厂商')),
                ('period', models.IntegerField(verbose_name='保质期天数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生产日期')),
                ('quality', models.IntegerField(verbose_name='产品质量')),
                ('game_id', models.IntegerField(verbose_name='游戏局id')),
                ('round_id', models.IntegerField(verbose_name='回合id')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField(verbose_name='商品id')),
                ('demands', models.IntegerField(verbose_name='需求量')),
                ('produce', models.IntegerField(verbose_name='生产量')),
                ('game_id', models.IntegerField(verbose_name='游戏局id')),
                ('round_id', models.IntegerField(verbose_name='回合id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(verbose_name='卖家id')),
                ('buyer_id', models.IntegerField(verbose_name='买家id')),
                ('good_id', models.IntegerField(verbose_name='商品id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='成交价')),
                ('game_id', models.IntegerField(verbose_name='游戏局id')),
                ('round_id', models.IntegerField(verbose_name='回合id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('character_id', models.SmallIntegerField(verbose_name='人物id')),
                ('health', models.SmallIntegerField(verbose_name='健康度')),
                ('energy', models.SmallIntegerField(verbose_name='精力值')),
                ('happiness', models.SmallIntegerField(verbose_name='快乐度')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='现金')),
                ('game_id', models.IntegerField(verbose_name='游戏局id')),
                ('round_id', models.IntegerField(verbose_name='回合id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField(verbose_name='商品id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='当前售价')),
                ('game_id', models.IntegerField(verbose_name='游戏局id')),
                ('round_id', models.IntegerField(verbose_name='回合id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(verbose_name='人物id')),
                ('object', models.IntegerField(verbose_name='对方id')),
                ('relation_code', models.IntegerField(verbose_name='0-陌生人 11-恋人  12-夫妻   21-父  22-母 31-子 32-女 41-兄 42-弟 43-姐 44-妹  51-同学  61-同事  71-聚会  81-酒吧 91-旅游')),
                ('game_id', models.IntegerField(verbose_name='游戏局id')),
                ('round_id', models.IntegerField(verbose_name='回合id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.IntegerField(verbose_name='1-零售 2-科技 3-不动产 4-运输 5-制造业 6-农林牧渔 7-资源')),
                ('type', models.SmallIntegerField(verbose_name='类型 0-实物 1-股票 2-虚拟物品')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('default', models.SmallIntegerField(verbose_name='默认关系值')),
                ('code', models.SmallIntegerField(verbose_name='code值')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
