# Generated by Django 3.0.8 on 2020-08-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='default',
            new_name='default_value',
        ),
        migrations.AlterField(
            model_name='game_goods',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='拥有者 0-匿名市场货物  '),
        ),
        migrations.AlterField(
            model_name='game_goods',
            name='quality',
            field=models.IntegerField(default=100, verbose_name='产品质量'),
        ),
    ]
