# Generated by Django 3.0.8 on 2020-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200812_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_Market',
        ),
        migrations.DeleteModel(
            name='Game_Price',
        ),
        migrations.RenameField(
            model_name='game_relationship',
            old_name='object',
            new_name='objecter',
        ),
        migrations.RemoveField(
            model_name='game_goods',
            name='isOnsale',
        ),
        migrations.RemoveField(
            model_name='game_goods',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='game_goods',
            name='period',
        ),
        migrations.RemoveField(
            model_name='game_goods',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='game_goods',
            name='quality',
        ),
        migrations.AddField(
            model_name='game_goods',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game_goods',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='type',
            field=models.SmallIntegerField(verbose_name='类型 1-实物 2-股票 3-虚拟物品'),
        ),
    ]
