# Generated by Django 3.0.8 on 2020-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200812_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField(verbose_name='商品id')),
                ('good_name', models.CharField(max_length=64)),
                ('demands', models.IntegerField(verbose_name='需求量')),
                ('produce', models.IntegerField(verbose_name='生产量')),
                ('game_id', models.IntegerField(verbose_name='游戏局id')),
                ('round_id', models.IntegerField(verbose_name='回合id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField(verbose_name='商品id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='当前售价')),
                ('game_id', models.IntegerField(verbose_name='游戏局id')),
                ('round_id', models.IntegerField(verbose_name='回合id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='game_relationship',
            old_name='objecter',
            new_name='objecter_id',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='default_value',
            new_name='default',
        ),
        migrations.RemoveField(
            model_name='game_goods',
            name='updated',
        ),
        migrations.AddField(
            model_name='game_goods',
            name='isOnsale',
            field=models.SmallIntegerField(default=0, verbose_name='是否在售'),
        ),
        migrations.AddField(
            model_name='game_goods',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='拥有者 0-匿名市场货物  '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_goods',
            name='period',
            field=models.IntegerField(default=1, verbose_name='保质期天数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_goods',
            name='producer',
            field=models.IntegerField(default=0, verbose_name='生产厂商'),
        ),
        migrations.AddField(
            model_name='game_goods',
            name='quality',
            field=models.IntegerField(default=1, verbose_name='产品质量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_orders',
            name='good_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_relationship',
            name='objecter_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_relationship',
            name='player_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game_goods',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='game_orders',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='成交价'),
        ),
        migrations.AlterField(
            model_name='game_player',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='现金'),
        ),
    ]
